// frontend/components/subjectSelect.tsx
import {useEffect, useState} from "react";
import {listSubjects, Subject} from "../api";
import React from "react";

interface Props {
    required: boolean;
    defaultValue?: number;
    onInput: (subject: number) => void;
}

export default function SubjectSelect({required, defaultValue, onInput}: Props) {
    const [subjects, setSubjects] = useState<Subject[] | null>(null);
    useEffect(() => {
        listSubjects().then(setSubjects);
    }, []);

    if (subjects === null) {
        return <></>;
    }

    return (
        <select
            required={required}
            defaultValue={defaultValue ?? "null"}
            onInput={(e) => {
                onInput(parseInt(e.currentTarget.value));
            }}
        >
            <option value="null" disabled={required}>{required ? "Pick a subject" : "None"}</option>
            {subjects.map((subject) => (
                <option key={subject.id} value={subject.id}>{subject.name}</option>
            ))}
        </select>
    );
}

// frontend/src/lib/components/SubjectSelect.svelte
<script lang="ts">
    export let subjects: {id: number; name: string}[];
    export let required: boolean = false;
    export let value = "null";
</script>

<select bind:value on:change {required}>
    <option disabled={required} value="null">{required ? "Pick a subject" : "None"}</option>
    {#each subjects as { id, name } (id)}
        <option value={id}>{name}</option>
    {/each}
</select>
